export const resList = [
  {
    id: "142670",
    name: "Shah Ghouse Hotel & Restaurant",
    cloudinaryImageId: "grqh1zb1kv8uhkmyercb",
    cuisines: ["Biryani", "Chinese", "Tandoor", "Mughlai"],
    avgRating: 4.3,
    deliveryTime: 30,
  },
  {
    id: "496680",
    name: "Shree Golden Palace Restaurant",
    cloudinaryImageId: "yhidqtj01vavz0wr7dty",
    cuisines: ["briyani", "South Indian", "Indian", "North Indian"],
    avgRating: 4.2,
    deliveryTime: 23,
  },
  {
    id: "4138",
    name: "Grand Hotel",
    cloudinaryImageId: "grqh1zb1kv8uhkmyercb",
    cuisines: ["Biryani", "Chinese", "Kebabs", "Tandoor"],
    avgRating: 4.4,
    deliveryTime: 31,
  },
  {
    id: "1004981",
    name: "Zoya's Kitchen",
    cloudinaryImageId: "yhidqtj01vavz0wr7dty",
    cuisines: ["Maharashtrian", "Beverages", "Street Food"],
    avgRating: 4.3,
    deliveryTime: 35,
  },
  {
    id: "654939",
    name: "Iqbal Cafe",
    cloudinaryImageId: "f594f4f63d3e00e93203f02d40e38d24",
    cuisines: ["Biryani"],
    avgRating: 4.5,
    deliveryTime: 33,
  },
  {
    id: "803234",
    name: "KLN Pickles",
    cloudinaryImageId: "grqh1zb1kv8uhkmyercb",
    cuisines: ["Biryani"],
    avgRating: 1.9,
    deliveryTime: 30,
  },
  {
    id: "874790",
    name: "Bawarchi Biryani And Shawarma",
    cloudinaryImageId: "yhidqtj01vavz0wr7dty",
    cuisines: ["Biryani"],
    avgRating: 3.4,
    deliveryTime: 39,
  },
];
